apiVersion: apps/v1
kind: Deployment
metadata: 
  name:  netflix-app
  labels: 
    app: netflix-app


spec:
  replicas: 2
  selector:
    matchLabels:
      app: netflix-app
  
  template:
    metadata: 
      labels: 
        app: netflix-app

    spec:
      containers:
        - image:  itsurvey6/netflix:24
          name: netflix-app
          ports:
          - name:  http
            containerPort:  3000
            protocol: TCP
